version: '3.8'
services:
  php:
    container_name: mage_php
    environment:
      - XDEBUG_MODE=develop,coverage
    image: mage_php
    build:
      context: "."
      dockerfile: "php/Dockerfile"
      args:
        UID: ${UID}
        GID: ${GID}
        PHP_VERSION: ${PHP_VERSION:-8.0}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - docker
    volumes:
      - mariadb-socket:/var/run/mysqld
      - ../:/app
      - ~/.config/composer/auth.json:/home/app/.composer/auth.json
      - ~/.ssh/:/home/app/.ssh:ro
  mariadb:
    container_name: mage_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=mage
      - MYSQL_DATABASE=mage
    image: mage_mariadb
    build:
      context: "."
      dockerfile: "mariadb/Dockerfile"
    healthcheck:
      test: "/usr/bin/mysql -uroot -pmage -e 'SHOW DATABASES;'"
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - mariadb-socket:/var/run/mysqld
networks:
  docker:
    name: docker
volumes:
  mariadb-socket:
  mariadb:
