version: '3.8'
services:
  php:
    environment:
      - XDEBUG_MODE=coverage
    build:
      context: "."
      dockerfile: "php/Dockerfile"
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - docker
    volumes:
      - mariadb-socket:/var/run/mysqld
      - ../:/app
  mariadb:
    container_name: mapi-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=mapi
      - MYSQL_DATABASE=mapi
    build:
      context: "."
      dockerfile: "mariadb/Dockerfile"
    image: mapi_mariadb
    healthcheck:
      test: "/usr/bin/mysql -uroot -pmapi -e 'SHOW DATABASES;'"
      timeout: 10s
      retries: 10
    ports:
      - "3307:3306"
    networks:
      docker:
        aliases:
          - database.local
    volumes:
      - mariadb:/var/lib/mysql
      - mariadb-socket:/var/run/mysqld
networks:
  docker:
    name: docker
volumes:
  mariadb-socket:
  mariadb:
